# Generated by Django 6.0 on 2025-12-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio_profiles', '0005_delete_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('EMBED', 'Embed')], default='IMAGE', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('update_type', models.CharField(choices=[('TRAINER_UPDATE', 'Trainer Update'), ('RACE_PREVIEW', 'Race Preview'), ('RACE_RESULT', 'Race Result')], default='TRAINER_UPDATE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('rendered_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_updates', to='studio_content.mediaasset')),
                ('horses', models.ManyToManyField(blank=True, related_name='updates', to='studio_profiles.horse')),
                ('owners', models.ManyToManyField(blank=True, related_name='updates', to='studio_profiles.owner')),
                ('primary_horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_updates', to='studio_profiles.horse')),
                ('trainers', models.ManyToManyField(blank=True, related_name='updates', to='studio_profiles.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block_type', models.CharField(choices=[('HEADING', 'Heading'), ('SUBHEADING', 'Subheading'), ('BODY', 'Body'), ('BULLETS', 'Bullets'), ('GREY_BOX', 'Grey Box')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('media_portrait', models.BooleanField(default=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='studio_content.mediaasset')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='studio_content.update')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
