# Generated by Django 6.0 on 2025-12-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='cover_media',
        ),
        migrations.RemoveField(
            model_name='update',
            name='summary',
        ),
        migrations.AddField(
            model_name='update',
            name='jockey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='update',
            name='public_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='update',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='race_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='race_track',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
