# Generated by Django 6.0 on 2025-12-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0002_remove_update_cover_media_remove_update_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Block Item', 'verbose_name_plural': 'Block Items'},
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'verbose_name': 'Media Library', 'verbose_name_plural': 'Media Library'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Content Blocks', 'verbose_name_plural': 'Content Blocks'},
        ),
    ]
