# Generated by Django 6.0 on 2025-12-22 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0003_alter_contentblock_options_alter_mediaasset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='public_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_library_entries', to='studio_content.update'),
        ),
    ]
