# Generated by Django 6.0 on 2025-12-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_content', '0004_mediaasset_is_finished_mediaasset_public_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Content Library', 'verbose_name_plural': 'Content Library'},
        ),
    ]
