# Generated by Django 6.0 on 2025-12-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='trainer',
        ),
        migrations.AddField(
            model_name='horse',
            name='nztr_url',
            field=models.URLField(blank=True, null=True, verbose_name='Love Racing NZ Profile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
