# Generated by Django 6.0 on 2025-12-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_profiles', '0002_remove_horse_owner_remove_horse_trainer_and_more'),
    ]

    operations = [
    ]
