# Generated by Django 6.0 on 2025-12-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_profiles', '0003_auto_20251222_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='nztr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndicate_name', models.CharField(default='First Gear Syndicate', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('revenue_share', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('min_token_size', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_profiles.horse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_profiles.owner')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_profiles.trainer')),
            ],
        ),
    ]
