# Generated by Django 6.0 on 2025-12-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio_profiles', '0004_alter_horse_nztr_url_lease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
