# Generated by Django 6.0 on 2025-12-22 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio_profiles', '0005_delete_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndicate_name', models.CharField(default='First Gear Syndicate', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('revenue_share', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio_profiles.horse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_profiles.owner')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio_profiles.trainer')),
            ],
        ),
    ]
