# Generated by Django 6.0 on 2025-12-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_months',
            field=models.PositiveIntegerField(default=12, help_text='Duration of lease in months'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
