# Generated by Django 6.0 on 2025-12-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_leases', '0002_lease_lease_months_alter_lease_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='PROPOSED', max_length=10),
        ),
    ]
