# Generated by Django 6.0 on 2025-12-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_leases', '0003_lease_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PROPOSED', max_length=10),
        ),
    ]
