# Generated by Django 6.0 on 2025-12-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio_leases', '0004_alter_lease_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='lease',
            name='syndicate_name',
            field=models.CharField(blank=True, help_text="Will auto-populate as '[Horse Name] Syndicate'", max_length=255),
        ),
    ]
